[workspace]
members = ["epis", "epis-core", "epis-stt", "epis-tts"]

[workspace.lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"

[workspace.lints.clippy]
missing_errors_doc = "warn"
missing_panics_doc = "warn"
missing_docs_in_private_items = "warn"
