[package]
name = "epis-stt"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["as_ref", "deref"] }
hound = "3.5.1"
thiserror = "2.0.16"
whisper-rs = { git = "https://codeberg.org/tazz4843/whisper-rs" }

[lints]
workspace = true
